services:
  - type: web
    name: mse2-exam-backend
    env: node
    root: backend
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start

  - type: web
    name: mse2-exam-frontend
    env: static
    root: frontend
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
